### ISSUE TITLE
Rebuild qaror on top of Discourse?

### ISSUE THREAD

**Issue by erlend-sh** [mateuszdw/qaror#5]
Please excuse my audacity, but have you considered rebuilding qaror on top of [Discourse](https://github.com/discourse/discourse)? (Built by people who used to work at StackOverflow).

It's primarily a discussion platform, but it can be extended to support other use cases.

https://meta.discourse.org/t/case-study-for-archetypes-questions-archetype/14527

Most of the necessary features are already there:
- User management
- Notifications
- Badges
- Trust levels
- E-mail done right
- Markdown
- Wiki posts
- Tags
- [Accepted answer](https://meta.discourse.org/t/discourse-solved-accepted-answer-plugin/30155)
- The list goes on...

A plugin that enabled SO-like features in Discourse would be a big deal. Check out the [Beginner’s Guide to Creating Discourse Plugins](https://meta.discourse.org/t/beginners-guide-to-creating-discourse-plugins/30515) if you're interested ;)

---

**Edit:** There's a ["Question and Answer" plugin](https://meta.discourse.org/t/question-answer-plugin/56032?u=erlend_sh) for Discourse now.

**Comment by mateuszdw** [comment]
I dont know how to bite it. I leave this topic open for some time.

**Comment by fabOnReact** [comment]
Hello, My name is Fabrizio and I found your project. Right now I have an Idea for a Coding Forum which should help people solve problems. I am a novice Ruby on Rails developer. I soon will launch my first project, which is not very good. It took me one month to develop, I hope that I will complete it in one week. https://barteringapps.herokuapp.com/
You can sign in with facebook or email, but sometimes heroku hibernates the app.

So I don't know if starting a new project or forking an existing one. I am thinking about it, because I am not very experienced and forking my second project may not be a good idea. 
Thanks a lot for your help in advance.
Fabrizio

**Comment by mateuszdw** [comment]
Hello Fabrizio,
I signed up to your project but can't confirm my email cause i didn't received it yet. 

I think, I don't understand the question :) 
You try to use qaror in your project but something went wrong?

It's little out of date but everything working fine on rails 3. Before digging deeper into it we should write more tests before upgrading to rails 4 or even 5. I definitely need some help to maintaining this project.

**Comment by fabOnReact** [comment]
Hello Matt,

I don't want to share your e-mail public hear, but I have it in my mail-box sent at 12:17 Paris Time, 2 hours ago. Sorry for contacting you so much in advance. Actually this is a totally different project, I just wanted to show it as I am a total novice on Rails so you could understand what I can do, what I can't and tell me if forking this project is appropriate for my knowledge or is it better to start all over, as sometimes building things is the better way to understand it. I work with rails since 2 months.
I just discovered your qaror project yesterday and I was thinking of forking. The only thing is that I use rails 5, I never written test but I have some training videos for that. Maybe I can check that out and think about it. It will take less time then building it from scratch for rails 5 right? and if I do not understand something you have a lot of experience!

Still I have a specific idea for coding forum in my mind.

**Comment by mateuszdw** [comment]
Yes it's from .pl domain

**Comment by mateuszdw** [comment]
You can fork the project or build it on new rails 5 scaffold and looking how some things are done. I think the biggest challenge in upgrading QARoR to rails 5 will be fighting with dependecies (but I could be wrong). You can also set up rails 5 in Gemfile and solve the errors (but i think it's not the good approach). Some extensions like in the lib/extender probably have already a gem for this. But also it has some adventages they are build-in. You don't have to use any voting or activity gems, just fix the rails 5 issues if any.

When I was building this app I was learning rails actually (and did not write tests at all). I tried to get the essence of question & answers platform not the old messy forums. When I almost finished most of q&a platform features I saw Discourse. It's good, it's one of the best modern discussion platform but mostly for users, not always for dev. I tried to look into Discourse when erlend-sh writes to me, it was big project already.
What I'm trying to say here is that I've injoy building this project, but at some point I should have been write a tests, especially for app/models/ability.rb. Unfortunately, I don't have time right know to workin out but I'm looking forward hear some news about your fork. 
Anyway, I can help you with some things which you will not be able to solve or work out from this project.

**Comment by erlend-sh** [comment]
p.s. there's actually a Question and Answer plugin for Discourse now:

https://meta.discourse.org/t/question-answer-plugin/56032?u=erlend_sh

The author of that plugin, @angusmcleod, is quite experienced in Rails/Ember and I'm sure he'd be happy to provide some mentorship to anyone interested in extending the plugin further.

**Comment by fabOnReact** [comment]
That is really great from both of you. So I am set up, I need to complete this project in maximum one week and get started with the Q&A. I will try to work with both github resources and I will try to do my best.
Thanks a lot. It is amazing and I would be happy to be part of some sort of community..
